version: '3.3'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NODE_PATH: /src/node_modules
      DEBUG: nodejs-docker-express:*
